#!/usr/bin/env python3
#coding: utf-8

############################################
#                MATHEMATICS               #
############################################
#                                          #
#  MONFA-MATAS Patricica & ROZET Corentin  #
#                                          #
#         Project : 203hotline_2019        #
#                                          #
############################################

from sys import argv

from usage import help
from compute import Math
from checkArgs import ArgumentManager
from hotline import Hotline


def main():

    argsManager = ArgumentManager()

    if argsManager.needHelp(argv):
        help()
    elif argsManager.checkArgs(argv) == 84:
        exit(84)
    else:
        hotline = Hotline()
        hotline.run()


if __name__ == "__main__":
    main()
