#!/usr/bin/env python3
#coding: utf-8

############################################
#                 B-CNA-410                #
############################################
#                                          #
#  MONFA-MATAS Patricica & ROZET Corentin  #
#                                          #
#            Project : Groundhog           #
#                                          #
############################################

from sys import argv

from checkArgs import ArgumentManager
from main import Groundhog

def main():

    argsManager = ArgumentManager()
    groundhog = Groundhog()

    if argsManager.needHelp(argv):
        groundhog.help()
    elif argsManager.checkArgs(argv) == 84:
        exit(84)
    else:
        groundhog.run()


if __name__ == "__main__":
    main()
